### ISSUE TITLE
Q: What is the shortened length?

### ISSUE THREAD

**Issue by MordiSacks** [mgrajcarek/uuid-shortener#16]
What is the shortened length?

**Comment by marmichalski** [comment]
Seems to be 1-22 characters. 🤔

**Comment by mgrajcarek** [comment]
Yes, it depends on a used dictionary - the larger it is, the shorter UUID can be generated.

**Comment by MordiSacks** [comment]
so it is not fixed to a specific size so for database scheme I guess i need to use varchar 255
Thanks everyone.
