### ISSUE TITLE
BigNumber replacement?

### ISSUE THREAD

**Issue by dereuromark** [mgrajcarek/uuid-shortener#4]
> Package moontoast/math is abandoned, you should avoid using it. Use brick/math instead.

Any plans on switching to brick/math instead?

**Comment by mgrajcarek** [comment]
Hi @dereuromark,
Thank you for a suggestion. I will give it a try :)

**Comment by mgrajcarek** [comment]
Thanks to @marmichalski brick/math is replacing moontoast/math.
