### ISSUE TITLE
Packagist repo did not pick up latest versions

### ISSUE THREAD

**Issue by Ocramius** [mgrajcarek/uuid-shortener#9]
https://packagist.org/packages/keiko/uuid-shortener didn't pick up `0.3.0`, `0.3.1` and `0.3.2` (released today): probably not synchronised?

**Comment by Ocramius** [comment]
Forced it to sync: needs auto-updating to be configured though.

**Comment by mgrajcarek** [comment]
Right, I will do it :)
Thanks.

**Comment by mgrajcarek** [comment]
Auto sync enabled.
